name: ci-backend

on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    env:
      EMAIL_BACKEND: django.core.mail.backends.console.EmailBackend
      EMAIL_HOST: smtp.gmail.com
      EMAIL_PORT: 587
      EMAIL_USE_TLS: 'True'
      EMAIL_HOST_USER: d79205927@gmail.com
      EMAIL_HOST_PASSWORD: ${{ secrets.EMAIL_HOST_PASSWORD }}
      DEFAULT_FROM_EMAIL: d79205927@gmail.com

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install PDM
        run: |
          curl -sSL https://pdm.fming.dev/install-pdm.py | python3
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Install dependencies with PDM
        run: pdm install

      - name: Run Django tests
        run: pdm run python manage.py test

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Docker image (no push)
        uses: docker/build-push-action@v2
        with:
          context: .
          push: false
